### ISSUE TITLE
Increase OTP validity

### ISSUE THREAD

**Issue by NaveenKS** [yashwanthm/cowin-vaccine-booking#54]
I was trying to understand how OTP expires. Currently it expires due to control policy i.e, Covin has set a limit on the number of requests that can repeatedly come from a single IP and if it crosses the limit, OTP would be invalidated. Same thing is happening currently as well. Get beneficiary is called every 10 seconds and after some request limit it expires. I was thinking is it possible to increase the OTP validity by not calling this API every 10 seconds? How about every 30 secs or 60 secs...Are there other reasons to do this way?

**Comment by yashtibrewal** [comment]
He is trying to check if the session is valid by called the beneficiary.
Yes, 60 seconds is a good value for a get beneficiary API, He must be changing it asap he reads this message.
If you have a better way to solve it, please go ahead and push your logic (pull request) so that he can go through it.

**Comment by yashwanthm** [comment]
OTP validity extention is impossible within the scope of this app. However, adjusted the poll freq to play within the rate limits. Update is deployed.
